/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui.test {
	import laya.ui.*;import laya.display.*; 
	import script/GameUI.ts;

	public class TestSceneUI extends Scene {

		override protected function createChildren():void {
			super.createChildren();
			loadScene("test/TestScene");

		}

	}
}